### Consider the below code to answer further questions:

In [35]:
import numpy as np

list_ = ["1", "2", "3", "4", "5"]
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [36]:
list_

['1', '2', '3', '4', '5']

In [37]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [38]:
# for array_list
print("Type:",type(array_list))

Type: <class 'numpy.ndarray'>


In [39]:
# for list_
print("Type:",type(list_))

Type: <class 'list'>


Ans. The data type of array_list variable is array that contains string elements, whereas list_ variable data type is list() that also contains string elements both array and list are different data types.
- **List**: A list in Python is a collection of items which can contain elements of multiple data types, which may be either numeric, character logical values, etc. It is an ordered collection supporting negative indexing. A list can be created using [] containing data values.
- **Array**: An array is a vector containing homogeneous elements i.e. belonging to the same data type. Elements are allocated with contiguous memory locations allowing easy modification, that is, addition, deletion, accessing of elements. In Python, we have to use the array module to declare arrays. If the elements of an array belong to different data types, an exception “Incompatible data types” is thrown.

### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [40]:
# for array_list
array_list.dtype # as array contains homogeneous elements that means all elements in the array will have the same data type

dtype('<U1')

In [41]:
# for list_
for i in list_:
    print(f"Data type of element at index {list_.index(i)} is {type(i)}")

Data type of element at index 0 is <class 'str'>
Data type of element at index 1 is <class 'str'>
Data type of element at index 2 is <class 'str'>
Data type of element at index 3 is <class 'str'>
Data type of element at index 4 is <class 'str'>


### Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [42]:
import numpy as np

array_list = np.array(object = list_, dtype = int)

In [52]:
# for array_list
array_list.dtype # as array contains homogeneous elements that means all elements in the array will have the same data type

dtype('int64')

In [53]:
# for list_
for i in list_:
    print(f"Data type of element at index {list_.index(i)} is {type(i)}")

Data type of element at index 0 is <class 'str'>
Data type of element at index 1 is <class 'str'>
Data type of element at index 2 is <class 'str'>
Data type of element at index 3 is <class 'str'>
Data type of element at index 4 is <class 'str'>


Ans. Yes, as while creating the array we have defined the dtype = int that means that array_list will contain elemnts that all are integer datatype, whereas list_ contains string datatype element.

### Consider the below code to answer further questions:

In [60]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [61]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [62]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

### Q4. Write a code to find the following characteristics of variable, num_array:

1. shape
2. size

In [66]:
num_array.shape

(2, 3)

In [64]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [73]:
arr0 = np.zeros((3,3))

In [74]:
arr0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
arr0.size

9

### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [76]:
arr_iden = np.eye(5)

In [77]:
arr_iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])